apiVersion: v2
name: gcp-compute-instance
version: 0.1.0
description: A Helm chart for deploying a standalone GCP Compute Engine virtual machine via Config Connector
type: application
icon: https://raw.githubusercontent.com/krateo-platformops/.github/main/brand/logo.svg
